spring:
  main:
    banner-mode: off
  application:
    name: customer-management-circuitbreaker
  jmx:
    enabled: true

logging:
  level:
    com.customermanagement.circuitbreaker: trace

server:
  port: 9091

customer-feign:
  getAllCustomers:
    url: /customers/getAll
  getCustomerById:
    url: /customers/{id}
  health:
    url: /actuator/health
  item:
    url: /item

feign:
  client:
    config:
      default:
        connectionTimeout: 30000
        loggerLevel: basic
        readTimeout: 30000

resilience4j:
  circuitbreaker:
    instances:
      customer-management:
        ignore-exceptions: feign.RetryableException,com.customermanagement.circuitbreaker.exception.BadRequestException,com.customermanagement.circuitbreaker.exception.CustomerInternalException,com.customermanagement.circuitbreaker.exception.NotAcceptableHeaderException,com.customermanagement.circuitbreaker.exception.NotFoundException
        minimum-number-of-calls: 5
        register-health-indicator: true
      orderService:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        automaticTransitionFromOpenToHalfOpenEnabled: true
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        waitDurationInOpenState: 5s
        slidingWindowType: COUNT_BASED

