#management:
#  health:
#    db:
#      enabled: true
#  endpoint:
#    health:
#      show-details: always
#  info:
#    git:
#      mode: full

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always