spring:
  main:
    banner-mode: off
  application:
    name: customer-management-circuitbreaker
  jmx:
    enabled: true

server:
  port: 9091

customer-feign:
  getAllCustomers:
    url: /customers/getAll
  getCustomerById:
    url: /customers/{id}
  health:
    url: /actuator/health

feign:
  client:
    config:
      default:
        connectionTimeout: 30000
        loggerLevel: basic
        readTimeout: 30000

resilience4j:
  circuitbreaker:
    instances:
      customer-management:
        ignore-exceptions: feign.RetryableException,com.customermanagement.circuitbreaker.exception.BadRequestException,com.customermanagement.circuitbreaker.exception.CustomerInternalException,com.customermanagement.circuitbreaker.exception.NotAcceptableHeaderException,com.customermanagement.circuitbreaker.exception.NotFoundException
        minimum-number-of-calls: 50
        register-health-indicator: true

